### ISSUE TITLE
[Dungeon] Dire Maul: West - Petrified Treant Abilities

### ISSUE THREAD

**Issue by Santah62** [KurthosWoW/TrinityCore#11]
**Description:**

Petrified Treant is missing an ability called "Harden Skin"

**Current behaviour:**

Petrified Treant is supposed to have an ability called Harden Skin but either doesn't have it or doesn't cast it
(https://classicdb.ch/?npc=11458#abilities)

**Expected behaviour:**

When fighting it is supposed to cast Harden Skin

**Steps to reproduce the problem:**

1. Enter Dire Maul: West
2. Fight Petrified Treant

**Comment by Santah62** [comment]
Its working, probably .die'd him before he was at 50%

**Comment by HelloKitty** [comment]
Confirmed working.
