### ISSUE TITLE
DMN - Missing Gordok Brute

### ISSUE THREAD

**Issue by Kurthos** [KurthosWoW/TrinityCore#118]
Gordok Brute is missing from a pack. Gordok Brute should spawn at my character position.

![image](https://user-images.githubusercontent.com/1082884/45482953-66a10a80-b78a-11e8-8f01-8a63a70181a1.png)

Here is a retail vanilla video image 

![image](https://user-images.githubusercontent.com/1082884/45482986-833d4280-b78a-11e8-9880-186ae8f6c3ab.png)

NPC Info for mob to the right of me:

SpawnID: 145884, current GUID low: 1014.
Entry: 11441.
Faction: 45.
NPC Flags: 1.
DisplayID: 12473 (Native: 12473).
Compatibility Mode: 0
Level: 58.
EquipmentId: 1 (Original: 1).
Health (base): 14355. (max): 14355. (current): 14355.
Movement type: Ground: Run, Swim: true, Flight: None
Unit Flags: 0
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 45.
SpawnTime: Full:1d Remaining:0s
Loot: 11441 Pickpocket: 11441 Skinning: 0
InstanceID: 1
Phasemask: 1
Armor: 3435
Position: 297.368011 -66.738098 -3.803760.
AIName: SmartAI ScriptName: 
React state: AGGRESSIVE
Active AI: class SmartAI
Flags Extra: 0
* has gossip (1)
MechanicImmuneMask: 0

**Comment by HelloKitty** [comment]
Doing a .gps and taking a screenshot would help too, assuming you aren't going to be the one to add him. Also, how did you grab the mob info? An addon to copy paste it?

**Comment by natnat201193** [comment]
.npc info   for the mob info.

**Comment by HelloKitty** [comment]
I know that, but how did he copy paste it lol.

**Comment by natnat201193** [comment]
ohhhh @HelloKitty  use the easycopy addon

**Comment by HelloKitty** [comment]
You guys and your addons, you got all the good stuff lol. I'll have to grab that too then.

**Comment by natnat201193** [comment]
```
DELETE FROM `creature` WHERE  `guid`=213818 AND `id`=11441;
INSERT INTO `creature` (`guid`, `id`, `map`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`) VALUES ('213818', '11441', '429', '1', '298.245270', '-71.463470', '-3.887040', '2.732579', '86400');
```

**Comment by natnat201193** [comment]
After Sorting out https://github.com/KurthosWoW/TrinityCore/issues/119 i Dont think there was actually a missing brute. i checked on retail and the path for ^ makes him go and stand next to the other brutes. so hes probably the one that seemed missing at the time. can leave the extra one there or remove it, your choice @Kurthos
