### ISSUE TITLE
[Dungeon] Dire Maul: West - Eldreth Apparition Abilities

### ISSUE THREAD

**Issue by Santah62** [KurthosWoW/TrinityCore#13]
**Description:**

Eldreth Apparition is missing an ability called [Chains of Ice]

**Current behaviour:**

Eldreth Apparition doesn't cast [Chains of Ice]
https://classicdb.ch/?npc=11471#abilities

**Expected behaviour:**

When fighting Eldreth Apparition it does not cast [Chains of Ice]

**Steps to reproduce the problem:**

1. Enter the ghost area of Dire Maul: West
2. Find an Eldreth Apparition
3. Fight it

**Comment by HelloKitty** [comment]
The ability using targeting called SMART_TARGET_HOSTILE_RANDOM_NOT_TOP meaning the creature will not cast it if there is nobody else on the threat table.

Working as intended.
