### ISSUE TITLE
[Dungeon] Dire Maul: West - Eldreth Phantasm Abilities

### ISSUE THREAD

**Issue by Santah62** [KurthosWoW/TrinityCore#14]
**Description:**

Eldreth Phantasm is missing the ability [Shrink]
https://classicdb.ch/?npc=11475#abilities

**Current behaviour:**

Eldreth Phantasm doesnt cast [Shrink]

**Expected behaviour:**

Eldreth Phantasm should cast [Shrink] while you're fighting it

**Steps to reproduce the problem:**

1. Go to the area of Dire Maul: West that has spirit enemies 
2. Fight an Eldreth Phantasm

**Comment by HelloKitty** [comment]
Right now the smart script is setup to cast it every 25 seconds. For such a punishing ability that requires a decurse this makes sense, so I will assume that the long initial cast delay AND the long random recast time is intended.
