### ISSUE TITLE
[Dungeon] Dire Maul: North - Bosses - Immunities

### ISSUE THREAD

**Issue by whammyresilience** [KurthosWoW/TrinityCore#142]
**Current behaviour:**

All bosses in Dire Maul: North are missing all immunities.

**Expected Behavior**

All bosses are missing immunities but should be immune to the following:
Charm (1)
Disoriented (2)
Disarm (4)
Distract (8)
Fear (16)
Grip (32)
Root (64)
Sleep (512)
Snare (1024)
Freeze (4096)
Knockout (8192)
Polymorph (65536)
Banish (131072)
Shackle (524288)
Turn Evil (4194304)
Horror (8388608)

[Cho'Rush the Observer](https://classicdb.ch/?npc=14324) should be susceptible to Fear (16), Freeze (4096), Polymorph (65536), Knockout (8192), Bleed (16384), and Horror (8388608) effects.

**Solution**

Guards, Stomper, Captain:
```
UPDATE creature_template SET mechanic_immune_mask = mechanic_immune_mask |1|2|16|32|64|512|1024|4096|8192|65536|8388608 WHERE entry IN (14326, 14322, 14321, 14323, 14325, 11501);
```

Cho'Rush:

```
UPDATE `creature_template` SET `mechanic_immune_mask` = `mechanic_immune_mask` |1|2|4|8|32|64|128|256|512|1024|2048|131072 WHERE `entry` = 14324;
```

^fixed 9/19/18 - Thanks Nyeriah!

**Comment by Nyeriah** [comment]
The first query is missing the IN operator 

``` UPDATEcreature_templateSETmechanic_immune_mask=mechanic_immune_mask64|512|1024|4096|8192|65536|8388608 WHERE entry IN (14326, 14322, 14321, 14323, 14325, 11501);
```

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/1dc62e07bda1f3ad7e6f7baf7f6495870fca67fa
