### ISSUE TITLE
[Dungeon] Dire Maul East: Old Ironbark/Ironbark the Redeemed is missing his script.

### ISSUE THREAD

**Issue by natnat201193** [KurthosWoW/TrinityCore#143]
when you first enter the instance, Old IronBark should be spawned in the Conservatory with this gossip: 
![wowscrnshot_091618_094408](https://user-images.githubusercontent.com/33712044/45595446-e1913d80-b9a3-11e8-8873-787992e71ec0.jpg)
Should also have the stunned animation. 

Once the boss Zevrim Thornhoof is dead, Old Ironbark will Yell "At last... Freed from his cursed grasp!" and then should be replaced with Ironbark the Redeemed. Ironbark the Redeemed has new gossip and once he is activated he will run to the door before the last boss and destroy it as seen here: https://www.youtube.com/watch?v=mLj9_dP1mRc&feature=youtu.be sorry for the lag, wasnt lagging ingame so idk why it is on the video. 

Old Ironbark NPC ID: 11491
Ironbark the Redeemed NPC ID: 14241

Side note:
The Door he is suppose to destroy is also Missing, should be spawned here:
<img width="350" alt="dire maul door" src="https://user-images.githubusercontent.com/33712044/45595550-c32c4180-b9a5-11e8-8a65-0b86537cc413.PNG">

When Ironbark activates the door, it needs to be activated as Alternative state for it to appear destroyed.

**Comment by HelloKitty** [comment]
Thanks, I will be fixing him soon. Tonight or tomorrow.

**Comment by natnat201193** [comment]
old ironbark is allready spawned in the correct place. what i would suggest, is to also spawn ironbark the redeemed in the same place, but have him phased out. doing it that way means we can just switch the phases around for both npc's instead of using spawn/despawn methods.

**Comment by HelloKitty** [comment]
Phasing didn't exist in Vanilla, what Vmangos does is call:
```
m_creature->UpdateEntry(NPC_IRONBARK_THE_REDEEMED);
```

Which basically turns him into another creature. It's very strange, but you can do that I guess.

**Comment by natnat201193** [comment]
what Vmangos does would actually be better. if we can do that with trinitycore

**Comment by natnat201193** [comment]
Door is now added. https://github.com/KurthosWoW/TrinityCore/commit/d2c62b67ec48fcd076c8b518b987e40c7b45db7f

**Comment by HelloKitty** [comment]
Is this the emote you're looking for? https://i.gyazo.com/1ddb493af507637f63d5c0439ac99004.gif

Or is it another "stunned" emote?

**Comment by HelloKitty** [comment]
Commit 854b38de75c190d852cdcf46ad994e56de97eee4 implements the event and addresses everything here.
