### ISSUE TITLE
[AQ20] Qiraji Swarmguard - Missing ability

### ISSUE THREAD

**Issue by Glonz** [KurthosWoW/TrinityCore#147]
Qiraji Swarmguard is not using abillity "Sundering Cleave".
(Cleave on next auto attack, which also reduces armor for 30 seconds, this does not stack)
Seems to cast roughly every 8 seconds

Creature ID 15343
Spell ID 25174

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/5a20d86bf9610916afd09ed86dd91f519c102167

**Comment by Glonz** [comment]
Seems to be working.
