### ISSUE TITLE
[AQ20] Hive'Zara Wasp - Missing ability

### ISSUE THREAD

**Issue by Glonz** [KurthosWoW/TrinityCore#149]
Hive'Zara Wasp is not casting "Itch".
(Spell that just ticks for 8 seconds and then turns into a poison DoT effect)
Should cast this on random players in range, likely roughly every 8 seconds.

Creature ID 15325
Spell ID 25185

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/d90e0d83b03111688c841a9c1bce68d6e16892e4

**Comment by Glonz** [comment]
Seems to be working.
