### ISSUE TITLE
[Dungeon] Dire Maul: West - Illyanna Ravenoak Abilities

### ISSUE THREAD

**Issue by Santah62** [KurthosWoW/TrinityCore#15]
**Description:**

Illyanna Ravenoak does not cast [Aimed Shot]
https://classicdb.ch/?npc=11488#abilities

**Current behaviour:**

Illyanna Ravenoak is missing the ability [Aimed Shot]

**Expected behaviour:**

Illyanna Ravenoak should cast [Aimed Shot] while you are fighting her

**Steps to reproduce the problem:**

1. Go up the ramp in the ghost area of Dire Maul: West
2. Fight Illyanna Ravenoak

**Comment by HelloKitty** [comment]
Spell ID 20904 now has a healing debuff added to the spell. However I will add that to the bosses abilities but I will not have her cast it often.

**Comment by HelloKitty** [comment]
Fixed
