### ISSUE TITLE
[Dungeon] Dire Maul: West - Illyanna Ravenoak Abilities

### ISSUE THREAD

**Issue by Santah62** [KurthosWoW/TrinityCore#16]
**Description:**

Illyanna Ravenoak's [Immolation Trap] Doesn't work properly

**Current behaviour:**

Illyanna Ravenoak places an [Immolation Trap] at the feet of her target

**Expected behaviour:**

Illyanna Ravenoak should place the [Immolation Trap] at her feet

**Steps to reproduce the problem:**

1. Go up the ramp in the the ghost area of Dire Maul: West
2. Pull Illyanna Ravenoak
3. Run around so you can see that she is placing it at your feet rather than hers

**Comment by HelloKitty** [comment]
Immolation trap is working. She is just not placing a visible trap, is it suppose to be visible? Otherwise the spell is working.

Re-open the issue if it's suppose to be visible.
