### ISSUE TITLE
[UBRS] Boss Gates

### ISSUE THREAD

**Issue by Kurthos** [KurthosWoW/TrinityCore#174]
Upon killing General Drakkisath, two gates should open up to allow players to zone out quickly to reset the instance. Currently the gates do not open.

87854 (Entry: 175946) - [Doodad_BOSSGATE01 X:45.193298 Y:-259.712006 Z:106.532997 MapId:229]  
Found nearby gameobjects (distance 10.000000): 1

87855 (Entry: 175947) - [Doodad_BOSSGATE02 X:45.193298 Y:-312.519989 Z:106.532997 MapId:229]  
Found nearby gameobjects (distance 10.000000): 1

Name: General Drakkisath
SpawnID: 137971, current GUID low: 69.
Entry: 10363.
Faction: 40.
NPC Flags: 0.
DisplayID: 10115 (Native: 10115).
Compatibility Mode: 0
Level: 62.
EquipmentId: 1 (Original: 1).
Health (base): 80925. (max): 80925. (current): 0.
Movement type: Ground: Run, Swim: true, Flight: None
Unit Flags: 64
UNIT_FLAG_UNK_6 (0x40)
Unit Flags 2: 2048.
Dynamic Flags: 5.
Faction Template: 40.
SpawnTime: Full:0s Remaining:106751991149507d22h34m35s
Loot: 10363 Pickpocket: 0 Skinning: 10363
InstanceID: 3
Phasemask: 1
Armor: 4391
Position: 36.450901 -285.993988 111.036003.
AIName:  ScriptName: boss_drakkisath
React state: AGGRESSIVE
Active AI: struct boss_drakkisath::boss_drakkisathAI
Flags Extra: 268435457
CREATURE_FLAG_EXTRA_INSTANCE_BIND (0x1)
CREATURE_FLAG_EXTRA_DUNGEON_BOSS (0x10000000)
MechanicImmuneMask: 617299803
MECHANIC_CHARM (0x1)
MECHANIC_DISORIENTED (0x2)
MECHANIC_DISTRACT (0x4)
MECHANIC_FEAR (0x5)
MECHANIC_ROOT (0x7)
MECHANIC_SILENCE (0x9)
MECHANIC_SLEEP (0xA)
MECHANIC_SNARE (0xB)
MECHANIC_STUN (0xC)
MECHANIC_FREEZE (0xD)
MECHANIC_KNOCKOUT (0xE)
MECHANIC_POLYMORPH (0x11)
MECHANIC_BANISH (0x12)
MECHANIC_SHACKLE (0x14)
MECHANIC_TURN (0x17)
MECHANIC_HORROR (0x18)
MECHANIC_DAZE (0x1B)
MECHANIC_SAPPED (0x1E)

**Comment by Nyeriah** [comment]
https://github.com/TrinityCore/TrinityCore/pull/22462/files
