### ISSUE TITLE
[Dungeon] Dire Maul: West - Illyanna Ravenoak Patrol

### ISSUE THREAD

**Issue by Santah62** [KurthosWoW/TrinityCore#18]
**Description:**

Illyanna Ravenoak doesn't patrol

**Current behaviour:**

Illyanna Ravenoak is idle

**Expected behaviour:**

Illyanna Ravenoak should patrol in an L shape from where she is standing to the Immol'thar Crsytal in the direction

**Steps to reproduce the problem:**

1. Go up the ramp in the ghost area of Dire Maul: West
2. Observe her not moving

**Comment by HelloKitty** [comment]
Take the dungeon map and draw a path or show me a video. I need more information.

**Comment by Santah62** [comment]
Couldn't find a map without writing on it, but this is pretty close to how she patrols
![illyanna](https://user-images.githubusercontent.com/37052916/45261510-1b75a900-b3d2-11e8-8380-39256304212c.png)

**Comment by HelloKitty** [comment]
Should she walk alone that line or just around in a circle in that general area?
