### ISSUE TITLE
[AQ20] Canal Frenzy - missing ability

### ISSUE THREAD

**Issue by Glonz** [KurthosWoW/TrinityCore#184]
**Description:**
Canal Frenzy is a trash mob found in the waters before Moam.

**Current behaviour:**
Not using ability Pierce Armor.

**Expected behaviour:**
Canal Frenzy should use Pierce Armor.

Creature ID 15505
Spell ID Pierce Armor 12097

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/24b4e85571338dea9eff228d0ca458d9ede6a0fb
