### ISSUE TITLE
[AQ20] Spitting Scarab - missing abilities

### ISSUE THREAD

**Issue by Glonz** [KurthosWoW/TrinityCore#188]
**Description:**
Spitting Scarab is a trash mob that appears before Moam, together with Shrieker Scarabs.

**Current behaviour:**
Doesn't use any abilities.

**Expected behaviour:**
Should use Berserker Change on random players in range and cast Acid Spit.

Creature ID 15462
Spell ID Berserker Charge 22886
Spell ID Acid Spit 24334

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/feff95af56c0ccd8929143cbf0702ce6573ff149

**Comment by Glonz** [comment]
Seems to be working now.
