### ISSUE TITLE
[Class][Hunter]: Feign Death does not remove the player from combat or reset threat with pet or or other party member in combat.

### ISSUE THREAD

**Issue by whammyresilience** [KurthosWoW/TrinityCore#2]
**Description:**

Hunter ability Feign Death is not resetting the hunter's threat when the pet is on a mob's threat table. 

**Current behaviour:**

When soloing a mob, Feign Death removes you from combat.
When soloing with your pet, Feign Death temporary removes you from the  threat but does not reset your threat to zero as it does in vanilla. 

**Expected behaviour:**

Regardless of how many people are in combat, solo or otherwise, Feign Death is a threat removal from the table completely until the hunter enters combat by pet attack or player attack. 

**Steps to reproduce the problem:**

Put yourself in combat with your pet or any other player in party and you can see this when you use FD.

**Comment by HelloKitty** [comment]
What is the hunter's feign death ID? There are a lot of spells with that name.

**Comment by whammyresilience** [comment]
5384: https://classicdb.ch/?spell=5384

**Comment by whammyresilience** [comment]
Closed due to what must have been a resist seen. Testing done in different location revealed everything to be working as intended.
