### ISSUE TITLE
[Dungeon] Dire Maul: West - Eldreth Spectre Abilities

### ISSUE THREAD

**Issue by Santah62** [KurthosWoW/TrinityCore#20]
**Description:**

Eldreth Spectre is missing the ability [Dark Offering]

**Current behaviour:**

Eldreth Spectre does not cast [Dark Offering]

**Expected behaviour:**

Eldreth Spectre should cast [Dark Offering] to heal itself

**Steps to reproduce the problem:**

1. Damage the Eldreth Spectre
2. Observe as nothing happens

**Comment by HelloKitty** [comment]
The smart script defines 3 dark offering casts that happen at various HP thresholds for friendly units excluding itself. Unless you can find something from Vanilla or Wotlk showing they cast it on themselves or they cast it multiple times in a repeatable manner, then it is working as intended.
