### ISSUE TITLE
[Rogue] Tier 1 8p set bonus not working

### ISSUE THREAD

**Issue by Glonz** [KurthosWoW/TrinityCore#206]
**Description:**
The 8 set bonus of the rogue's Tier 1 Nightslayer armor allows the rogue to heal for 500 health when Vanish is used.

**Current behaviour:**
When a rogue casts vanish with 8 Nightslayer set pieces equipped, nothing else happens.

**Expected behaviour:**
The rogue should be healed for 500 health when Vanish is used.

Item Set ID Nightslayer Armor 204
Tier 1 8p set healing (Clean Escape) Spell ID 23582
Spell ID Vanish Rank 1 1856
Spell ID Vanish Rank 2 1857
Spell ID Vanish Rank 3 26889

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/e1cf4953f71b9ccd5263c13d65c814c4054fe733
