### ISSUE TITLE
[Paladin] Tier 1 8p set bonus - not working correctly

### ISSUE THREAD

**Issue by Glonz** [KurthosWoW/TrinityCore#209]
**Description:**
The 8 set bonus of the paladin's Tier 1 Lawbringer armor allows the paladin to gain a chance at a party-wide heal effect on each attack. 

**Current behaviour:**
The heal effect currently procs on every single hit.

**Expected behaviour:**
The proc rate should be much lower. I suggest that something like 15% on each hit should be good enough, considering that the Tier 1 paladin set is inferior to many other gear choices.

Itemset ID Lawbringer Armor 208
Spell ID Lawbringer 21747

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/fb5865792743052bb4cb759039d5f13bc97ce069
