### ISSUE TITLE
[Dungeon] Dire Maul: West - Shen'dralar Spirit Faction

### ISSUE THREAD

**Issue by Santah62** [KurthosWoW/TrinityCore#21]
Shen'dralar Spirits should have the Shen'dralar faction rather than Undercity

**Comment by HelloKitty** [comment]
There are 2 Shendralar factions with ID 1355 and 1354. I don't know which one to pick, so I'll pick 1354.

**Comment by HelloKitty** [comment]
Fixed, I think.
