### ISSUE TITLE
[Paladin] Tier 2 8p set bonus - not working

### ISSUE THREAD

**Issue by Glonz** [KurthosWoW/TrinityCore#210]
**Description:**
The 8 set bonus of the paladin's Tier 2 Judgement armor enables the paladin to deal bonus damage when he hits an enemy with a Judgement.

**Current behaviour:**
No bonus damage is dealt when the paladin hits an enemy with a Judgement while wearing eight pieces of Tier 2 armor.

**Expected behaviour:**
Every Judgement that hits an enemy should trigger a bonus damage spell if the paladin wears 8 pieces of Tier 2 armor.

Itemset ID Judgement Armor 217
Spell ID Judgement (8p set bonus) 23591
Spell ID Judgement of Light 20271
Spell ID Judgement of Justice 53407
Spell ID Judgement of Wisdom 53408

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/2597ee37cfad79a0bf2ffbf411df0b26d7f5ab96
