### ISSUE TITLE
[Paladin] AQ20 class set bonus - not working

### ISSUE THREAD

**Issue by Glonz** [KurthosWoW/TrinityCore#212]
**Description:**
The 3 set bonus of the paladin's AQ20 Battlegear of Eternal Justice gives the paladin a 20% chance to regain extra mana on a Judgement cast.

**Current behaviour:**
No mana is gained on any Judgement cast, the spell does not work.

**Expected behaviour:**
Every Judgement cast should give the paladin a 20% chance to gain 100 mana through a certain spell proc when he is wearing all 3 pieces of the AQ20 class set.

Itemset ID Battlegear of Eternal Justice 506
Spell ID Battlegear of Eternal Justice (AQ20 class set bonus) 26135
Spell ID Judgement of Light 20271
Spell ID Judgement of Justice 53407
Spell ID Judgement of Wisdom 53408

**Comment by Nyeriah** [comment]
https://github.com/TrinityCore/TrinityCore/issues/22503
