### ISSUE TITLE
[Warlock] Tier 3 2p set bonus - not working correctly

### ISSUE THREAD

**Issue by Glonz** [KurthosWoW/TrinityCore#220]
**Description:**
The 2 set bonus of the warlock's Tier 3 Plagueheart raiment gives the warlock a chance to receive a heal whenever Shadow Bolt hits an enemy.

**Current behaviour:**
The heal currently procs 100% on every Shadow Bolt.

**Expected behaviour:**
Wowhead comments suggest that the heal should have a proc chance of roughly 10% (when the warlock wears 2 pieces of the Plagueheart set and hits an enemy with Shadow Bolt).

Itemset ID Plagueheart Raiment 529
Spell ID Vampirism 28831 (2 set bonus)

**Comment by Nyeriah** [comment]
https://github.com/KurthosWoW/TrinityCore/commit/984b796e8eae9cf9b9748e0758ec08cb1d0e77a6
