### ISSUE TITLE
[Dungeon] Dire Maul: West - Arcane Torrent Abilities

### ISSUE THREAD

**Issue by Santah62** [KurthosWoW/TrinityCore#23]
**Description:**

Arcane Torrents Lightning Cloud interrupts itself

**Current behaviour:**

Arcane Torrents can't finish casting Lightning Cloud

**Expected behaviour:**

Arcane Torrents should finish casting and place an AoE above their target

**Steps to reproduce the problem:**

1. Pull an Arcane Torrent 
2. Wait for it to cast Lightning Cloud
3. Watch it interrupt itself

**Comment by HelloKitty** [comment]
Seems to be working, maybe try testing again in the future?
