### ISSUE TITLE
Debuff shows as Buff on player target

### ISSUE THREAD

**Issue by Keoqt** [KurthosWoW/TrinityCore#28]
**Description:**

Debuff shows up as buff on my player

**Current behaviour:**

![image](https://user-images.githubusercontent.com/43097758/45257624-a8583c80-b3a9-11e8-8a07-a2acce802639.png)

**Expected behaviour:**

Should be show up as a debuff

**Comment by HelloKitty** [comment]
Listing the spellid or the creature that casts it would be helpful.

**Comment by Keoqt** [comment]
![image](https://user-images.githubusercontent.com/43097758/45257716-e570fe80-b3aa-11e8-84de-af0b583bf587.png)

Risen Guard: NPC-Id: 10489

**Comment by HelloKitty** [comment]
The issue is fixed, I'm considering a possible PR to TC to get their input as well.
