### ISSUE TITLE
Core/Spell: Spells with SPELL_AURA_MOD_RESISTANCE that would usually be negative are a buff.

### ISSUE THREAD

**Issue by HelloKitty** [KurthosWoW/TrinityCore#30]
**Description:**

SPELL_AURA_MOD_RESISTANCE should be a debuff sometimes but isn't.

**Current behaviour:**

SPELL_AURA_MOD_RESISTANCE spells which have negative level scaling component aren't being considered in the Buff vs Debuff spell determination. 

**Expected behaviour:**

SPELL_AURA_MOD_RESISTANCE spells which have negative level scaling components should be debuffs.

This is the root cause of issue #28 . Affects probably many spells.

**Comment by natnat201193** [comment]
h

**Comment by natnat201193** [comment]
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130057/spell+custom+attr

**Comment by HelloKitty** [comment]
I have created a fix that should work at the aura mod level. It should also address other latent issues with debuffs being considered buffs for miss chance and other stuff.
