### ISSUE TITLE
[Spell] Ashbringer Should be none removable.

### ISSUE THREAD

**Issue by natnat201193** [KurthosWoW/TrinityCore#32]
Spell ID: 28282 https://classicdb.ch/?spell=28282 Ashbringer should be none removable by the player.
Currently the spell can be Right clicked off with the weapon still equipped.

The aura should only be applied and removed by equipping and unequipping the Weapon https://classicdb.ch/?item=22691

**Comment by HelloKitty** [comment]
Is it suppose to be a buff first? Not a debuff? Hmmm, I'll have to look into how to make buffs non-debuffable.

**Comment by HelloKitty** [comment]
Maybe SPELL_ATTR0_PASSIVE?

**Comment by natnat201193** [comment]
it is allready a buff and after looking in to it, it seems that is correct, so just needs making none removable, this can be done in the SpellMgr

    ApplySpellFix({ 28282 }, [](SpellInfo* spellInfo)
    {
        spellInfo->Attributes |= SPELL_ATTR0_CANT_CANCEL;
    });

its allready a passive

**Comment by natnat201193** [comment]
however, i dont know if the above code will affect the weapon its self removing it. it shouldnt though

**Comment by HelloKitty** [comment]
I can push it to the test realm if you to test right now if you want.

**Comment by natnat201193** [comment]
Thisi can be closed now, seems to work perfect :D

**Comment by HelloKitty** [comment]
Closed because commit 4bdc833 fixed it.
