### ISSUE TITLE
Dungeon: Dire Maul North Buffs Not Working

### ISSUE THREAD

**Issue by HelloKitty** [KurthosWoW/TrinityCore#36]
None of the NPCs have their gossip to grant the buffs.

**Comment by Keoqt** [comment]
You kept all the guards alive?

**Comment by natnat201193** [comment]
i managed to get all three buffs when doing tribute

**Comment by Keoqt** [comment]
testing it now

**Comment by Keoqt** [comment]
![image](https://user-images.githubusercontent.com/43097758/45260120-cd1ad700-b3de-11e8-903f-0a1f044e8db3.png)

![image](https://user-images.githubusercontent.com/43097758/45260126-e02da700-b3de-11e8-8205-32adb34456ef.png)

**Comment by Keoqt** [comment]
Works for me

**Comment by HelloKitty** [comment]
Yea, it was actually working already. I was just level 80 and the buffs don't work about 60 or 63 or something.
