### ISSUE TITLE
[Dungeon] Dire Maul: North - Knot Thimblejack spawn location incorrect

### ISSUE THREAD

**Issue by whammyresilience** [KurthosWoW/TrinityCore#5]
**Description:**

Knot Thimblejack spawns above on the 2nd tier platform, not attached to the ball and chain below near Slip'kik's path.

**Current behaviour:**

He spawns on the second tier behind a group of ogres.

**Expected behaviour:**

He should appear attached to the ball and chain on the lower level. 

**Steps to reproduce the problem:**

See him in Dire Maul: North.

**Comment by HelloKitty** [comment]
Is that the only problem with him? We don't need to release him? Or do something to get his gossip to become active? I just have to move him?

**Comment by HelloKitty** [comment]
Position has been fixed as of bf80fecf0238aeb074f0ff94a69321b2d26dc8a2 . Pathing is probably not correct though.
