### ISSUE TITLE
Bosses you can Mind Control

### ISSUE THREAD

**Issue by CharlesH1994** [KurthosWoW/TrinityCore#57]
**Description:**
Bosses you can Mind control:
Stratholme:
Archivist Galford (High Damage Spamable Skills) 
Blackrock Depths:
Houndmaster Grebmar
Pyromance Loregrain (Spamable damage skill)
Warder Stilgis (Spamable aoe CC)
Fineous Darkvire
Golemlord argelmach
Ribbley Screwspigot
Hurley Blackbreath
Dire Maul East:
Lethtendris
Pimgib (Spamable damage skill, Also a imp showing as humanoid)
Isalien
Dire Maul North:
Guard Mol'dar (Spamable damage skill)
Guard fendgus (Spamable damage/CC skills)
Guard slip'kik (spamable cc skill)
Captain Kromcrush (High damage spamable skill)
King Gordok (High damage/CC/Aoe Skills)
Cho'Rush the Observer
 Lower Blackrock Spire:
Spirestone Butcher
Spirestone Battlelord
Spirestone Magus (CC,Buff,damage)
Bannok Grimaxe
Quatermaster Zigris (Spamable AoE CC)
Upper Blackrock Spire:
Goraluk Anvilcrack (Spamable CC)
Jed Runewatcher (spamable  CC damage)

**Current behaviour:**

If these mobs are all considered "bosses" they should not be able to get Mind Controlled

**Expected behaviour:**

Immune to Mind Control

**Steps to reproduce the problem:**

1.Go to instance and Mind Control
2. Use mob to solo bosses/mobs
3. get free loots

**Comment by HelloKitty** [comment]
Good find! I will look into making any boss creature immune to mind control globally. Then if we find a case of something that should be MC-able we will add a case for that. Would likely better faster than adding MC immune to each individual creature.

**Comment by natnat201193** [comment]
most immunities are still a thing on retail for things like this so can be tested. at least the bosses that are still available.

**Comment by natnat201193** [comment]
Tested dire maul north: all bosses are immune to taunt including Stomper Kreeg which is not on the list

**Comment by natnat201193** [comment]
This will add MC immune for all of the above:
```
UPDATE `creature_template` SET `mechanic_immune_mask` = `mechanic_immune_mask` | 1 WHERE `entry` IN
(10811, 9319, 9024, 9041, 9056, 8983, 9543, 9537, 14327, 14349, 16097, 14326, 14321, 14323, 14325, 11501, 14324, 14322, 9219, 9218, 9217, 9596, 9736, 10899, 15796, 10509);
```

**Comment by natnat201193** [comment]
i think trying to make every boss immune to mind control would be more trouble than its worth, because bosses that show the level instead of a skull dont have the boss flag as far as im aware. and i think this immunity is allready part of the boss flag that is used for raid bosses ect.
