### ISSUE TITLE
[Dungeon] Dire Maul: North - Kromcrush's Guardians do not have a threat table. 

### ISSUE THREAD

**Issue by whammyresilience** [KurthosWoW/TrinityCore#6]
**Current behaviour:**

You cannot taunt or build threat on these NPCs.

**Expected behaviour:**

They should have a working threat table. 

**Steps to reproduce the problem:**

Attack the mob and have someone taunt it off or pull threat off you.

**Comment by HelloKitty** [comment]
This may be a general issue with summoned minions. I can't find any information on it yet.

**Comment by HelloKitty** [comment]
Confirmed all summoned creatures don't have threat.

**Comment by HelloKitty** [comment]
Going to reopen a more general issue related to this.
