### ISSUE TITLE
[Dungeon] Dire Maul: North - Guard Fengus is missing Some abilities

### ISSUE THREAD

**Issue by natnat201193** [KurthosWoW/TrinityCore#7]
Current behaviour:
https://vanillawowdb.com/?spell=20691, https://vanillawowdb.com/?spell=22572 and https://vanillawowdb.com/?spell=15655 is missing.

Expected behaviour:
should use all three :p

**Comment by HelloKitty** [comment]
I wonder if there is any information on how often he should use these.

**Comment by HelloKitty** [comment]
These are 3.3.5 abilities too, so it's not vanilla addition.

**Comment by HelloKitty** [comment]
Can't find any information on the stun, I assume it's not cast on the tank?

Also, I found in this video that he is charging players but I'm not sure what server this is on and if it is correct. https://www.youtube.com/watch?v=Ff3sbtG48oc

**Comment by natnat201193** [comment]
these may indeed be abilities added later on.
These are what is being used on the lightshope repack. could also be wrong ofc.
enum
{
    // For ALL
    SPELL_KNOCK_AWAY            = 10101,
    SPELL_SHIELD_CHARGE         = 15749,
    SPELL_STRIKE                = 14516,    
    SPELL_SHIELD_BASH           = 11972,
    SPELL_GUARD_ENRAGE          = 8269,

    // Guard Fengus
    SPELL_FENGUS_FEROCITY       = 22817,
    SPELL_ICE_LOCK              = 22856,

    // Guard Slip'kik
    SPELL_SLIPKIKS_SAVVY        = 22820,

    // Guard Mol'dar
    SPELL_MOLDAR_MOXIE          = 22818,

    EMOTE_ENRAGE                = -1900040,
};
