### ISSUE TITLE
[Dungeon] Blackrock Depths - The Lyceum/The Iron Hall Doors/Brazier - Room Mechanics

### ISSUE THREAD

**Issue by whammyresilience** [KurthosWoW/TrinityCore#74]
**Description:**

Shadowforge Flame Keepers have an item called Shadowforge Torch. This item should be used twice to light both braziers at the opposite end of the hall from which you enter, before Magmus' room (The Iron Hall). 

**Current behaviour:**

Currently one brazier opens the door and allows access.

**Expected behaviour:**

The doors are not supposed to open until both braziers are lit, not one at a time. 

**Steps to reproduce the problem:**

Kill the Shadowforge Flame Keeper, loot one torch, light the brazier, and the door opens.

**Comment by Nyeriah** [comment]
https://github.com/TrinityCore/TrinityCore/pull/22472
