### ISSUE TITLE
[Class] Rogue D2 4pc procc rate

### ISSUE THREAD

**Issue by Jaxson123** [KurthosWoW/TrinityCore#80]
Current behaviour:
The current proccrate of d2 4pc from the rogue/dark mantle set seems to be very off.
Over the course of 5 minutes ive got a total of 3045 energy in total from those proccs.

https://imgur.com/a/ODg9C1z

sometimes i was even able to procc the 35 energy procc twice

Expected behaviour:

I am not sure what the exact proccrate of it is supposed to be, just seems to be way off and it would make aquiring other pieces obsolete as you would always want to use 4pc atleast from that set

Steps to reproduce the problem:

Equip the set and monitor the energy proccs on the dummy for a while.
Might consult other rogue players though as the setbonus could have its intended procc rate.

**Comment by KarazhanSucks** [comment]
Vanilla proc rate was probably 3.5% flat.

Standard TC is 3 ppm. Primal nerfed it to 1.5 ppm for balancing.

Hold off on modifying/altering these chances 'till we get a firm and final talent tree lock setup.

**Comment by Glonz** [comment]
I cannot do legit DPS parses on pre-raid gear with the broken proc rate on this set bonus.

SpellID from set bonus 27787 which triggers energy gain spell
dungeon set 1 and 2 itemset ID 184 and 512

through some quick autoattack testing
2.0 speed 300 attacks 28 procs 
3.0 speed 200 attacks 25 procs
6.0 speed 100 attacks 37 procs

even without considering all this, getting ~18 procs in a minute (3045 energy in 5 minutes) shows that the proc rate is insane lol. either adjust the %procrate or ppm or whatever

without this fix, there is not going to be any talent tree lock setup to wait around for

**Comment by natnat201193** [comment]
things to be made to work correctly first. should never base class tuning on something thats got a broken proc rate.
